sudo: required
services:
  - docker

before_install:
  - docker build -t lvl39/react-test -f ./client/Dockerfile.dev ./client

script:
  -  docker run -e CI=true lvl39/react-test npm test

after_success:
  - docker build -t lvl39/multi-client ./client
  - docker build -t lvl39/multi-nginx ./nginx
  - docker build -t lvl39/multi-server ./server
  - docker build -t lvl39/multi-worker ./worker

  # Log in to the docker CLI
  - docker login -u "$DOCKER_ID" -p $DOCKER_PASSWORD

  # Take those images and push them to docker hub
  - docker push lvl39/multi-client
  - docker push lvl39/multi-nginx
  - docker push lvl39/multi-server
  - docker push lvl39/multi-worker